### ISSUE TITLE
Panic when running depster resolve with multi-document YAML file

### ISSUE THREAD

**Issue by timflannagan** [benluddy/depster#22]
When running the v1.2.0 depster release locally, a panic was produced when passing a YAML file that contains multiple manifests:

```console
$ ./depster resolve scratch/*.yaml
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/operator-framework/operator-lifecycle-manager/pkg/controller/registry/resolver.(*SatResolver).SolveOperators(0xc0001d4040, {0x0, 0x0, 0x0}, {0x0, 0x767600c00033d100, 0x0}, {0xc000788a58, 0x1, 0x1})
	/home/tflannag/go/pkg/mod/github.com/operator-framework/operator-lifecycle-manager@v0.20.0/pkg/controller/registry/resolver/resolver.go:65 +0x1391
github.com/benluddy/depster/cmd/internal/resolve.AddTo.func1(0xc000511b80, {0xc00042f610, 0x1, 0x1})
	/home/tflannag/Documents/operator-framework/depster/cmd/internal/resolve/resolve.go:89 +0x665
github.com/spf13/cobra.(*Command).execute(0xc000511b80, {0xc00042f540, 0x1, 0x1})
	/home/tflannag/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000511900)
	/home/tflannag/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/tflannag/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/benluddy/depster/cmd.Execute()
	/home/tflannag/Documents/operator-framework/depster/cmd/root.go:17 +0xe9
main.main()
	/home/tflannag/Documents/operator-framework/depster/main.go:10 +0x19
```

The scratch directory contained a single YAML file that has the following structure:

<details>

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/packageA.ff-e2e-fl6mv: ""
  name: stubtk9fx-sub
  namespace: ff-e2e-fl6mv
spec:
  channel: stable
  name: packageA
  source: stubtk9fx
  sourceNamespace: ff-e2e-fl6mv

---

apiVersion: v1
kind: Namespace
metadata:
  name: ff-e2e-fl6mv

---

apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: fbc
  namespace: ff-e2e-fl6mv
spec:
  sourceType: grpc
  address: localhost:50051
```

</details>

This seems like a relatively straight forward fix for adding multi-document YAML file parsing, or calling this out in the help description that depster only support a single Kubernetes API per YAML file.
